spring:
  application:
    name: application
  config:
    import: optional:configserver:http://localhost:8888


server:
  port: 8081

logging:
  level:
    org.springframework.cloud.config.client: DEBUG
